name: ami
description: Portfolio For Subrota Debnath with flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animation_progress_bar: ^2.3.1
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.4
  go_router: ^12.0.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  internet_connection_checker_plus: ^2.0.0
  intl: ^0.18.1
  logger: ^2.0.2
  scrollable_positioned_list: ^0.3.8
  shimmer: ^3.0.0


dev_dependencies:
  bloc_test: ^9.1.3
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  mockito: ^5.4.2



flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

